server:
  port: 0

spring:
  main:
    web-application-type: reactive
  application:
    name: R-SERVICE

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096

      get-student-by-grade-book-number-topic:
        name: get-student-by-grade-book-number-topic
        partitions: 3
        replicas: 3

      get-all-students-request-topic:
        name: get-all-students-request-topic
        partitions: 3
        replicas: 3

      get-student-by-grade-book-number-response-topic:
        name: get-student-by-grade-book-number-response-topic

      get-all-students-response-topic:
        name: get-all-students-response-topic

    producer:
      acks: all
      delivery-timeout-ms: 20000
      linger-ms: 0
      request-timeout-ms: 10000
      idempotence: true
      max-in-flight-requests-per-connections: 5

    consumer:
      group-id: get-student-results
      max-poll-interval-ms: 300000 # 5 минут
      session-timeout-ms: 10000


  data:
    redis:
      port: 6379
      host: localhost

ws:
  host:
    localhost
  port:
    8085
  prefix:
    soap
  student-endpoint:
    StudentService


scheduler:
  thread-cap: 10
  queued-task-cap: 100
  name: blocking

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/